[[bond]]
source = "tpknam1qpqmtm23apgv089yztgh5ecaecw5ufydc9dx4vpmjjz9n5j7hryhvc9zrfg"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "80"

[bond.signatures]
tpknam1qpqmtm23apgv089yztgh5ecaecw5ufydc9dx4vpmjjz9n5j7hryhvc9zrfg = "signam1qrcz99337rt7r54taghn83qf5xpc2c48em0fuu3fw2m0vcpjz4467ur04vw7pczdwjncp0qqggd8vwz0udv5a4wy9djdc3chh8nnlhc8amnchx"


[[bond]]
source = "tpknam1qpqmtm23apgv089yztgh5ecaecw5ufydc9dx4vpmjjz9n5j7hryhvc9zrfg"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "20"

[bond.signatures]
tpknam1qpqmtm23apgv089yztgh5ecaecw5ufydc9dx4vpmjjz9n5j7hryhvc9zrfg = "signam1qzh5skuprtccs7wjrfyy203tw33hyxz0e4pr88dz036vf2e98r9t3r666lcn2dzld6a6j72rwhxp87vqn07ar8sc6tmw8zx7qj0suucfyz59a3"
